### ISSUE TITLE
open ros2bag error

### ISSUE THREAD

**Issue by iceriver97** [ZWhuang666/MIAS-LCEC#6]
打开ros2bag 时异常退出：
```
camera/image_raw/compressed,sensor_msgs/msg/CompressedImage
/rslidar_points,sensor_msgs/msg/PointCloud2
find one image

>>> [rcutils|error_handling.c:108] rcutils_set_error_state()
This error state is being overwritten:

  'Handle's typesupport identifier (rosidl_typesupport_cpp) is not supported by this library, at ./src/type_support_dispatch.hpp:111'

with this new error message:

  'Fast CDR exception deserializing message of type sensor_msgs::msg::dds_::Image_., at ./src/type_support_common.cpp:118'

rcutils_reset_error() should be called after error handling to avoid this.
<<<
terminate called after throwing an instance of 'rclcpp::exceptions::RCLError'
  what():  Failed to deserialize ROS message.: Fast CDR exception deserializing message of type sensor_msgs::msg::dds_::Image_., at ./src/type_support_common.cpp:118
mias_lcec.sh: 第 9 行：  6398 已中止               （核心已转储） $SCRIPT_DIR/bin/C/zvision
```

**Comment by ZWhuang666** [comment]
zvision用的是sensor_msgs::msg::Image进行反序列化，但是您的压缩格式是sensor_msgs::msg::compressedImage，目前暂不支持这种格式。过段时间会开源一个ros2的读取程序，我们会改进现有的功能并增加更多的格式支持。

**Comment by iceriver97** [comment]
> zvision用的是sensor_msgs::msg::Image进行反序列化，但是您的压缩格式是sensor_msgs::msg::compressedImage，目前暂不支持这种格式。过段时间会开源一个ros2的读取程序，我们会改进现有的功能并增加更多的格式支持。

使用autocalibration始终没有正确结果：
```
wq@wq-PC:~/faw.ai/MIAS-LCEC-main$ sh ./mias_lcec.sh
EXE_ABS_PATH: /home/wq/faw.ai/MIAS-LCEC-main/bin
DPA_CHECKPOINT_PATH /home/serilk/ZLcMatch/Zvision2/src/zvisionpython/weights/depth_anything_v2_vitb.pth
config_path /home/wq/faw.ai/MIAS-LCEC-main/bin/python/config.json
/home/wq/faw.ai/MIAS-LCEC-main/bin/python/config.json
Config file is {'path': {'ros': '/bin/python', 'conda': '/usr/local/lib/python3.10/dist-packages', 'sam': '/home/wq/faw.ai/MIAS-LCEC-main/bin/MobileSAM'}, 'Debug': {}}
/home/wq/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
config.json  not found!picRenderChoice not found
picRenderChoice not found.
picRenderChoice not found in the json file!
picRenderChoice not found
picRenderChoice not found.
test1
Intrinsic not found
Intrinsic.K not found.
Intrinsic.K  not found!
Intrinsic not found
Intrinsic.D not found.
Intrinsic.D  not found!
Extrinsic not found
Extrinsic.R not found.
Extrinsic.R  not found!
Extrinsic not found
Extrinsic.T not found.
Extrinsic.T  not found!
pygame 2.6.1 (SDL 2.28.4, Python 3.10.12)
Hello from the pygame community. https://www.pygame.org/contribute.html
/home/wq/.local/lib/python3.10/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/home/wq/.local/lib/python3.10/site-packages/timm/models/registry.py:4: FutureWarning: Importing from timm.models.registry is deprecated, please import via timm.models
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.models", FutureWarning)
/home/wq/faw.ai/MIAS-LCEC-main/bin/MobileSAM/mobile_sam/modeling/tiny_vit_sam.py:656: UserWarning: Overwriting tiny_vit_5m_224 in registry with mobile_sam.modeling.tiny_vit_sam.tiny_vit_5m_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
/home/wq/faw.ai/MIAS-LCEC-main/bin/MobileSAM/mobile_sam/modeling/tiny_vit_sam.py:656: UserWarning: Overwriting tiny_vit_11m_224 in registry with mobile_sam.modeling.tiny_vit_sam.tiny_vit_11m_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
/home/wq/faw.ai/MIAS-LCEC-main/bin/MobileSAM/mobile_sam/modeling/tiny_vit_sam.py:656: UserWarning: Overwriting tiny_vit_21m_224 in registry with mobile_sam.modeling.tiny_vit_sam.tiny_vit_21m_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
/home/wq/faw.ai/MIAS-LCEC-main/bin/MobileSAM/mobile_sam/modeling/tiny_vit_sam.py:656: UserWarning: Overwriting tiny_vit_21m_384 in registry with mobile_sam.modeling.tiny_vit_sam.tiny_vit_21m_384. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
/home/wq/faw.ai/MIAS-LCEC-main/bin/MobileSAM/mobile_sam/modeling/tiny_vit_sam.py:656: UserWarning: Overwriting tiny_vit_21m_512 in registry with mobile_sam.modeling.tiny_vit_sam.tiny_vit_21m_512. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
The number of dir to img save path is : 22
[INFO] [1733397486.961616030] [ZMsgNode]: Hello,Node:ZMsgNode online!
the No.1 task start, waiting for command from C++ Node......
test1
start setparas
[INFO] [1733397539.375059236] [ZcNode]: ZV_MessageNode created.
[INFO] [1733397539.375683438] [ZcNode]: iviewer Publishing: '{
    "mateCommand":["startMating","/home/wq/faw.ai/MIAS-LCEC-main/data/wh2075/cal/1733105860.531248569/itr1/1733105860.531248569_c.jpg","/home/wq/faw.ai/MIAS-LCEC-main/data/wh2075/cal/1733105860.531248569/itr1/1733105860.531248569_o.jpg","/home/wq/faw.ai/MIAS-LCEC-main/data/wh2075/cal/1733105860.531248569/itr1"]
}
'
received command: {
    "mateCommand":["startMating","/home/wq/faw.ai/MIAS-LCEC-main/data/wh2075/cal/1733105860.531248569/itr1/1733105860.531248569_c.jpg","/home/wq/faw.ai/MIAS-LCEC-main/data/wh2075/cal/1733105860.531248569/itr1/1733105860.531248569_o.jpg","/home/wq/faw.ai/MIAS-LCEC-main/data/wh2075/cal/1733105860.531248569/itr1"]
}

received command: {
    "mateCommand":["startMating","/home/wq/faw.ai/MIAS-LCEC-main/data/wh2075/cal/1733105860.531248569/itr1/1733105860.531248569_c.jpg","/home/wq/faw.ai/MIAS-LCEC-main/data/wh2075/cal/1733105860.531248569/itr1/1733105860.531248569_o.jpg","/home/wq/faw.ai/MIAS-LCEC-main/data/wh2075/cal/1733105860.531248569/itr1"]
}

The received camera_src shape is : (2160, 3840, 3),start mobile_sam ....
The received camera_src shape is : (2160, 3840, 3),start mobile_sam ....
string published successfully.
[INFO] [1733397542.392910933] [ZV_Node]: ZV_MessageNode created.
waiting for message...
cal mobile_sam cost:  221.2060570716858
cal mobile_sam cost:  229.3105034828186
ResImgSavePath =  /home/wq/faw.ai/MIAS-LCEC-main/data/wh2075/cal/1733105860.531248569/itr1/camera/
panel shape (2160, 3840, 3)
my process cost:  12.137609004974365
camera VMap create done
The received lidar_src shape is : (2160, 3840, 3),start mobile_sam...
ResImgSavePath =  /home/wq/faw.ai/MIAS-LCEC-main/data/wh2075/cal/1733105860.531248569/itr1/camera/
panel shape (2160, 3840, 3)
my process cost:  15.609494686126709
camera VMap create done
The received lidar_src shape is : (2160, 3840, 3),start mobile_sam...
cal mobile_sam cost:  217.81750655174255
ResImgSavePath =  /home/wq/faw.ai/MIAS-LCEC-main/data/wh2075/cal/1733105860.531248569/itr1/lidar/
panel shape (2160, 3840, 3)
my process cost:  4.036453723907471
lidar VMap create done
cores ind num  70
node match pairs num:  6
[INFO] [1733398002.763640334] [ZV_Node]: string received'{
"Points1":[1149,847,1149,847,1149,847,1149,847,1149,847,1149,847],
"Points2":[1114,798,1120.5,803.5,1172.5,950.5,1041.5,944.5,1104.5,801.5,1113,799]
}'
Python time=463.406s
<Error> The available points pairs is less that 4, not enough!

start to sample points
---------------Samp Points Result--------------
Initial point3d num: 0 |  num after sample: 0
Initial point2d num: 0 |  num after sample: 0
start to get combination
[INFO] [1733398002.868454556] [ZMsgNode]: Hello,Node:ZMsgNode online!
the No.5 task start, waiting for command from C++ Node......
Segmentation fault (core dumped)
wq@wq-PC:~/faw.ai/MIAS-LCEC-main$ cal mobile_sam cost:  218.7135353088379
ResImgSavePath =  /home/wq/faw.ai/MIAS-LCEC-main/data/wh2075/cal/1733105860.531248569/itr1/lidar/
panel shape (2160, 3840, 3)
my process cost:  2.3821558952331543
lidar VMap create done
cores ind num  70
/home/wq/faw.ai/MIAS-LCEC-main/bin/python/c3m.py:9: RuntimeWarning: invalid value encountered in divide
  LcMatchCApi()
node match pairs num:  6
received command: {
"Points1":[1149,847,1149,847,1149,847,1149,847,1149,847,1149,847],
"Points2":[1114,798,1120.5,803.5,1172.5,950.5,1041.5,944.5,1104.5,801.5,1113,799]
}
Traceback (most recent call last):
  File "/home/wq/faw.ai/MIAS-LCEC-main/bin/python/c3m.py", line 9, in <module>
    LcMatchCApi()
  File "LcMatch_CApi.py", line 579, in code.LcMatch_CApi.LcMatchCApi
  File "LcMatch_CApi.py", line 243, in code.LcMatch_CApi.AutoLcMatch_CApi_Auto
KeyError: 'mateCommand'
[WARN] [1733398010.377413057] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
[INFO] [1733398010.379783288] [ZMsgNode]: Hello,Node:ZMsgNode online!
the No.2 task start, waiting for command from C++ Node......

```
相机分割结果如下：
![seg_arr](https://github.com/user-attachments/assets/d3137a03-ab79-404c-959a-440aa634b5bc)
雷达分割结果如下：

![seg_arr](https://github.com/user-attachments/assets/0f481dfa-88a2-46ee-b243-8f5d9362d913)
想问一下雷达分割结果跟`KeyError: 'mateCommand'`是什么原因？

**Comment by iceriver97** [comment]
[1733105860.531248569.zip](https://github.com/user-attachments/files/18022565/1733105860.531248569.zip)
pcd文件

**Comment by ZWhuang666** [comment]
首先从图片上感觉您的点云和相片拍摄位置差异太大了，传感器之间的公共视野较小。其次json文件中虚拟相机的内参配置最好和真实相机的接近（尽可能一致）。如果激光雷达点云分割结果像您给出的那样太差的话，点云和相机图像之间难以完成正确的特征点匹配，导致无法完成标定。目前的算法在固态雷达采集的稠密点云上表现比较好。如果点云太稀疏，标定精度会大幅下降。

**Comment by ZWhuang666** [comment]
首先从图片上感觉您的点云和相片拍摄位置差异太大了，传感器之间的公共视野较小。其次出现了KeyError: 'mateCommand'代表您的json文件应该没有正确读取，可以发一下您的json文件内容。

在标定的json文件配置中虚拟相机的内参配置最好和真实相机的接近（尽可能一致）。如果激光雷达点云投影和相机相片差异过大，或是点云投影的分割结果太差，会导致点云和相机图像之间难以完成正确的特征点匹配，导致无法完成正确的标定。目前的算法在固态雷达采集的稠密点云上表现比较好。如果点云太稀疏，标定精度会大幅下降。

**Comment by iceriver97** [comment]
感谢回复！传感器本身的共视区域应该是够的，您可以看一下上传的pcd文件，与相机的分割图对的上；
[test_wh2075.json](https://github.com/user-attachments/files/18032010/test_wh2075.json)
解释一下json文件，因为我的相机畸变参数是8参数模型，不是plumb_bob的5参数模型，所以基于原来的相机内参及8参数畸变参数，使用cv::getOptimalNewCameraMatrix得到了新的内参矩阵（如json中所示），同时在自动标定选择图像文件时使用了此方法去畸变后的图像，此时认为plumb_bob模型的5个畸变参数为`[0.0],[0.0],[0.0],[0.0],[0.0`
最后，我感觉点云图像的方向上是不是差了180度，从分割图像上可以看到正前方有一堵墙，怀疑是从墙的后面投影到传感器的方向，造成了其他在传感器与墙之间的物体无法被利用。

**Comment by iceriver97** [comment]
此雷达为速腾M2雷达，不算太稀疏。

**Comment by ZWhuang666** [comment]
您可以把相机原始图片发给我么？我跑一下看看

**Comment by iceriver97** [comment]
> 您可以把相机原始图片发给我么？我跑一下看看

感谢，您方便提供一下邮箱吗？

**Comment by ZWhuang666** [comment]
好的，仓库主页的这个zhiwei.huang@outlook.com就是我的邮箱
